channels:
- conda-forge
dependencies:
- python=3.8.16
- pip<=21.3.1
- pip:
  - mlflow==2.4
  - cloudpickle==2.2.1
  - psutil==5.8.0
  - scikit-learn==1.0.2
  - typing-extensions==4.6.3
name: mlflow-env
